name: continuous deploy

on:
  push:
    branches:
      - main

jobs:
  release-charts:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the source code
        uses: actions/checkout@v3

      - uses: wistia/parse-tool-versions@v1.0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
