name: pr_build
on:
  pull_request:
    paths:
      - '*'
      - '*/**'
      - '!README.md'
      - '!.tool-versions'
      - '!COPYING.LGPL-3'
      - '!.gitattributes'
      - '!.gitignore'


jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: wistia/parse-tool-versions@v1.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          # Not pushing - this is just to test the build
          push: false
          tags: ghcr.io/${{ github.repository_owner }}:latest,ghcr.io/${{ github.repository_owner }}:${{ env.RELEASE_VERSION }}


  build-binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: wistia/parse-tool-versions@v1.0

      - uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GOLANG_TOOL_VERSION }}"

      # intentionally not pushing, this is just
      # to test the command
      - run: make build-binaries

  skaffold:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: wistia/parse-tool-versions@v1.0

      - name: start minikube
        uses: hiberbee/github-action-minikube@1.7.0

      - name: setup helm
        uses: hiberbee/github-action-helm@1.13.0

      - name: run skaffold
        uses: hiberbee/github-action-skaffold@1.24.0
        with:
          skaffold-version: "${{ env.SKAFFOLD_TOOL_VERSION }}"
          command: run
