name: go ci
on:
  pull_request:
    paths:
      - '.github/workflows/on_pull_request_go.yaml'
      - 'Makefile'
      - '*/**.go'
      - '*.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  ci-golang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: wistia/parse-tool-versions@v1.0

      - uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GOLANG_TOOL_VERSION }}"

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@${{ env.STATICCHECK_TOOL_VERSION }}

      - run: make lint test-golang
